-- Create comprehensive sample data for social media platform
-- This script will populate the database with 30 posts (10 each of photo, video, text)
-- Created by 5 different users with diverse content and global locations

-- Clear existing data
DELETE FROM posts;
DELETE FROM users;

-- Insert sample users
INSERT INTO users (username, email, password_hash, display_name, avatar_url) VALUES
('alex_wanderer', 'alex@wanderlust.com', '$2b$12$LQv3aWD9yXN8MLqB6r2YdL1QGTj5JY9Q', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop'),
('maya_photographer', 'maya@pixel.com', '$2b$12$LQv3aWD9yXN8MLqB6r2YdL1QGTj5JY9Q', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop'),
('james_creator', 'james@creative.com', '$2b$12$LQv3aWD9yXN8MLqB6r2YdL1QGTj5JY9Q', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop'),
('sarah_vlogr', 'sarah@stories.com', '$2b$12$LQv3aWD9yXN8MLqB6r2YdL1QGTj5JY9Q', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop'),
('david_writer', 'david@words.com', '$2b$12$LQv3aWD9yXN8MLqB6r2YdL1QGTj5JY9Q', 'David Writer', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop');

-- Photo Posts (10)
INSERT INTO posts (user_id, username, display_name, avatar_url, content_type, content, caption, likes, comments, reposts, filter_tags, location) VALUES
(1, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1551882547-5c40-5723-90a1de9e3b1?w=600&h=600&fit=crop', 'Mountain sunrise at dawn 🏔️ The perfect way to start the day. Nature never disappoints! #nature #photography #mountains', 1247, 89, 34, '["nature","photography","mountains","sunrise"]', 'Swiss Alps'),
(2, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1519904981063-cfafb5d7394?w=600&h=600&fit=crop', 'Urban exploration in Tokyo 🌃 Every corner tells a story. Love the vibrant energy of this city! #urban #photography #tokyo', 892, 67, 23, '["urban","photography","tokyo","architecture"]', 'Tokyo, Japan'),
(3, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=600&fit=crop', 'Desert dunes golden hour 🌅 Nature''s masterpiece! The silence here is golden. #desert #landscape #photography', 2156, 145, 89, '["desert","landscape","photography","goldenhour"]', 'Sahara Desert'),
(4, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1551882547-5c40-5723-90a1de9e3b1?w=600&h=600&fit=crop', 'Northern lights magic 🌌 The universe putting on a show! Simply breathtaking! #aurora #nature #photography #norway', 3421, 234, 156, '["aurora","nature","photography","norway"]', 'Tromsø, Norway'),
(5, 'sarah_vlogr', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'Tropical paradise found 🏝️ Crystal clear waters and white sand beaches. Pure bliss! #beach #tropical #paradise', 1876, 98, 67, '["beach","tropical","paradise","travel"]', 'Maldives'),
(6, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1551882547-5c40-5723-90a1de9e3b1?w=600&h=600&fit=crop', 'Autumn forest walkway 🍂 Nature''s carpet of gold! Fall is my favorite season. #autumn #forest #nature', 1654, 112, 78, '["autumn","forest","nature","fallcolors"]', 'Vermont, USA'),
(7, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'Misty morning lake reflection 🌅 Nature''s perfect mirror at sunrise! #nature #landscape #photography', 2341, 189, 89, '["nature","landscape","photography","reflection"]', 'Banff National Park, Canada'),
(8, 'sarah_vlogr', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop', 'Sakura blooming in Kyoto 🌸 Spring''s delicate beauty captured in pixels! #cherryblossom #japan #nature', 1567, 134, 76, '["cherryblossom","japan","nature","spring"]', 'Kyoto, Japan'),
(9, 'david_writer', 'David Writer', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1551882547-5c40-5723-90a1de9e3b1?w=600&h=600&fit=crop', 'Golden gate bridge sunset 🌅 San Francisco''s iconic beauty! Even more stunning in person. #california #photography #travel', 2876, 178, 89, '["california","photography","travel","sanfrancisco"]', 'San Francisco, CA'),
(10, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'photo', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'Snowy mountain peaks at dusk 🏔️ Winter''s rugged beauty never fails to impress! #mountains #winter #photography', 1654, 112, 78, '["mountains","winter","photography","snow"]', 'Aspen, Colorado');

-- Video Posts (10)
INSERT INTO posts (user_id, username, display_name, avatar_url, content_type, content, caption, likes, comments, reposts, filter_tags, location) VALUES
(1, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', 'Mountain biking adventure! 🚵‍♂️ Challenging trails and rewarding views. Adventure awaits! #mountainbiking #outdoor #adventure', 2103, 187, 92, '["mountainbiking","outdoor","adventure","sports"]', 'Moab, Utah'),
(2, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'Time-lapse city life 🌃 The urban rhythm never stops! #timelapse #urban #citylife', 3542, 298, 145, '["timelapse","urban","citylife","photography"]', 'New York City'),
(3, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'Ocean waves and coastal vibes 🌊 There''s something calming about the rhythm of the sea. #ocean #coastal #relaxation', 1789, 134, 76, '["ocean","coastal","relaxation","nature"]', 'Big Sur, California'),
(4, 'sarah_vlogr', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', 'Wildlife documentary moments 🦁 Capturing nature''s most precious encounters. #wildlife #documentary #nature', 4321, 267, 189, '["wildlife","documentary","nature","animals"]', 'Serengeti National Park'),
(5, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'Space exploration documentary 🚀 Journey to the stars and beyond! #space #science #exploration', 5634, 412, 234, '["space","science","exploration","documentary"]', 'Kennedy Space Center'),
(6, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'Underwater coral reef exploration 🐠 Ocean''s hidden world revealed! Marine conservation spotlight. #ocean #marineconservation #underwater', 2341, 189, 76, '["ocean","marineconservation","underwater","coralreef"]', 'Great Barrier Reef, Australia'),
(7, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBike.mp4', 'Epic mountain biking journey 🚵‍♂️ From alpine meadows to rocky peaks! This adventure tested every limit. #mountainbiking #adventure #epic', 1890, 456, 234, '["mountainbiking","adventure","epicjourney"]', 'Alps, France'),
(8, 'sarah_vlogr', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerDramas.mp4', 'Rainforest drone cinematography 🚁 Aerial views of the world''s lungs! Conservation through technology. #rainforest #conservation #drone', 3123, 234, 167, '["rainforest","conservation","drone","aerial"]', 'Amazon Rainforest'),
(9, 'david_writer', 'David Writer', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'African safari wildlife documentary 🦁 The circle of life in all its raw beauty! Respect our planet''s inhabitants. #wildlife #documentary #safari', 5634, 345, 189, '["wildlife","documentary","safari","africa"]', 'Serengeti National Park'),
(10, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'video', 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'Northern lights chase adventure 🌌 Nature''s greatest show pursued across three countries! Eight nights of aurora hunting magic! #aurora #northernlights #adventure', 6234, 456, 432, '["aurora","northernlights","adventure","norway"]', 'Tromsø, Norway');

-- Text Posts (10)
INSERT INTO posts (user_id, username, display_name, avatar_url, content_type, content, caption, likes, comments, reposts, filter_tags, location) VALUES
(1, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'text', 'Just finished reading "Sapiens" by Yuval Noah Harari. Mind-blowing perspective on human history and our future!\n\nKey takeaways:\n• Agriculture was humanity''s biggest revolution\n• We''re living in the most peaceful era ever\n• AI may change everything, but humans remain fundamentally the same\n\nHighly recommended for anyone interested in where we came from and where we''re going!\n\nWhat''s the most profound insight you''ve gained from a book? #books #history #learning', 'Mind-expanding read 📚 "Sapiens" completely changed how I view human history. Harari''s insights about agriculture, peace, and AI are fascinating. Have you read it? What book changed your perspective? #books #history #learning', 892, 234, 156, '["books","history","learning","sapiens"]', 'Home Office'),
(2, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'text', 'Climate update: The latest IPCC report is both terrifying and hopeful. Terrifying data, but solutions exist. We have the technology, funding, and knowledge. What we lack is the collective will.\n\nKey findings:\n• Warming is accelerating faster than predicted\n• Renewable energy is now cheaper than fossil fuels\n• Every 0.1°C matters immensely\n\nThe question isn''t "can we" but "will we". #climate #science #action', 'Climate reality check 🌍 Latest IPCC report is sobering but solutions exist. We have the technology, what we need is the will. Every fraction of a degree matters! #climate #science #sustainability', 2341, 567, 345, '["climate","science","sustainability","ipcc"]', 'United Nations Climate Conference'),
(3, 'james_creator', 'James Creator', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop', 'text', 'Startup lessons after 5 years, 2 failed companies, and 1 successful exit:\n\n1. Your first idea is rarely your best idea\n2. Culture eats strategy for breakfast\n3. Sleep is a competitive advantage\n4. The best team isn''t always the most talented\n5. Success is moving target posts, not hitting them\n\nWishing every founder the wisdom I learned the hard way! #startup #entrepreneurship #lessons', '5 years of startup wisdom 💡 1 failed company, 2 failed companies, 1 exit. Here''s what I learned about building businesses. #startup #entrepreneurship #lessons', 3456, 789, 432, '["startup","entrepreneurship","lessons","business"]', 'Silicon Valley'),
(4, 'sarah_vlogr', 'Sarah Vlogger', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop', 'text', 'The creative process is messy, non-linear, and deeply personal. I used to think "real artists" worked in straight lines. Now I know creativity is chaos with purpose.\n\nMy creative routine:\n• Morning pages - no expectations, just movement\n• Walks with no phone - let mind wander\n• "Useless" creation - play without pressure\n• Show up consistently - inspiration favors the working\n\nEmbracing the beautiful mess of creating something from nothing! #creativity #art #process', 'The beautiful mess of creativity 🎨 Embracing the chaos in my creative process. Realizing that art isn''t about perfection, but about showing up consistently. #creativity #art #writing', 1567, 234, 178, '["creativity","art","process","writing"]', 'Art Studio'),
(5, 'david_writer', 'David Writer', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop', 'text', 'Digital minimalism update: 1 year with 100 items, and my life has never been better. The paradox: having less gives you more of what matters.\n\nWhat I kept:\n• Quality over quantity\n• Experiences over things\n• Relationships over digital noise\n• Time over money\n\nWhat I learned: Freedom isn''t having what you want, it''s wanting what you have. #minimalism #digitaldetox #lifestyle', '1 year of digital minimalism 🧘 My life with 100 items vs 1000+. The paradox of having less giving me more of what matters. #minimalism #digitaldetox #lifestyle', 2876, 345, 234, '["minimalism","digitaldetox","lifestyle","simplicity"]', 'Minimalist Apartment'),
(6, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'text', 'Travel changed me. It''s not about Instagram photos or souvenirs. It''s about realizing how small the world is, and how big our problems. It''s about understanding that privilege and perspective are the ultimate luxuries.\n\nMost transformative experiences:\n• Teaching English to monks in Thailand\n• Getting lost in Tokyo at 2 AM\n• Sharing meals with families in refugee camps\n• Realizing education is the great equalizer\n\nTravel doesn''t change you, it reveals you. #travel #perspective #gratitude', 'How travel reveals your true self 🌍 5 years of transformative journeys that shaped who I am today. It''s not about destinations, but about perspective shifts. #travel #perspective #gratitude', 4123, 567, 432, '["travel","perspective","gratitude","transformation"]', 'Remote Workspace'),
(7, 'alex_wanderer', 'Alex Wanderer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', 'text', 'The paradox of modern connection: We have more connections than ever, yet studies show record levels of loneliness. Something isn''t adding up.\n\nMy thoughts:\n• Social media connects us but doesn''t fulfill us\n• We''re optimizing for efficiency at the cost of meaning\n• Maybe the solution isn''t more apps, but deeper conversations\n\nWhat do you think? How do you combat modern loneliness? #philosophy #life #mentalhealth', 'Deep thoughts on modern connection 🤔 We''re more connected yet more isolated than ever. Is social Media the problem or the solution? #philosophy #mentalhealth #society', 1203, 445, 234, '["philosophy","mentalhealth","society","socialmedia"]', 'Coffee Shop'),
(8, 'maya_photographer', 'Maya Photographer', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop', 'text', 'Photography business insights 💰 10 years behind the lens: pricing, marketing, client relations, industry changes.\n\nHard lessons learned:\n• Never work for "exposure" - always get paid\n• Your best marketing is your portfolio, not your ads\n• Specialize in what you love most\n• Business skills are as important as creative skills\n\nCurrent rates: $200/hr commercial, $75/hr portraits, pricing available upon request\n\nBuilding my dream studio in 2024! #photography #business #entrepreneurship', 'Photography business insights 💰 10 years behind the lens: pricing, marketing, client relations, industry changes.\n\nHard lessons learned:\n• Never work for "exposure" - always get paid\n• Your best marketing is your portfolio, not your ads\n• Specialize in what you love most\n• Business skills are as important as creative skills\n\nCurrent rates: $200/hr commercial, $75/hr portraits, pricing available upon request\n\nBuilding my dream studio in 2024! #photography #business #entrepreneurship', 1567, 134, 178, '["photography","business","entrepreneurship","pricing"]', 'Photography Studio, Portland');